### ISSUE TITLE
edd-api stats requests fail with date ranges other than yesterday, today

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6505]
### Expected behavior
When I request data from the API with `this/last_week, this/last_month, this/last_quarter, this/last_year` I should get the data as a JSON response.

### Actual behavior
Currently errors with a PHP Fatal error.

### Steps to reproduce the behavior
1) Make a request like the following: `/edd-api/stats?key=<api key>&token=<api token>&type=earnings&date=this_week`

Error log entry:
```
[13-Apr-2018 06:58:15 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in easy-digital-downloads/includes/api/class-edd-api.php:1413
Stack trace:
#0 easy-digital-downloads/includes/api/class-edd-api.php(569): EDD_API->get_stats(Array)
#1 /wordpress-4.9.5/wp-includes/class-wp-hook.php(286): EDD_API->process_query(Object(WP))
#2 /wordpress-4.9.5/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /wordpress-4.9.5/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#4 /wordpress-4.9.5/wp-includes/class-wp.php(726): do_action_ref_array('wp', Array)
#5 /wordpress-4.9.5/wp-includes/functions.php(960): WP->main('')
#6 /wordpress-4.9.5/wp-blog-header.php(16): wp()
#7 /wordpress-4.9.5/index.php(17): require('/wordpress-4.9....')
#8 {main}
  thrown in easy-digital-downloads/includes/api/class-edd-api.php on line 1413
```

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 2.9 (maybe lower, but affecting current live version)

WordPress Version: 4.9.4

Any other relevant information: I don't think this is specific to a version of PHP, WP, or EDD, so just test on `masters` and what not.

**Comment by SDavisMedia** [comment]
Testing.

**Comment by SDavisMedia** [comment]
I definitely replicated the errors on `master`. On `issue/6505`, the errors are fixed (properly returning JSON responses) and the pseudo-date ranges are returning data properly, including pseudo-date ranges that span across weeks, months, and years.

Looking good as far as I can tell! :+1:
