### ISSUE TITLE
PHP fatal error: Call to undefined method EDD\Logs\Log::get_meta()

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6751]
### Expected behavior
In `release/3.0`, when viewing Downloads > Downloads, if I click the number in the Sales column for a product, I expect it to work.

### Actual behavior
It throws this fatal error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method EDD\Logs\Log::get_meta() in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-sales-logs-list-table.php:203
Stack trace:
#0 /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-base-logs-list-table.php(336): EDD_Sales_Log_Table->get_logs(Array)
#1 /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/tools/logs.php(49): EDD_Base_Log_List_Table->prepare_items()
#2 /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/tools/logs.php(103): edd_logs_view_page(Object(EDD_Sales_Log_Table), 'sales')
#3 /app/public/wp-includes/class-wp-hook.php(286): edd_logs_view_sales('')
#4 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /app/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/tools.php(1605): do_action('edd_logs_view_s...')
#7 /app/public/wp-includes/class-wp-h in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-sales-logs-list-table.php on line 203
```

### Steps to reproduce the behavior
1) Go to Downloads > Downloads 
2) Click the Sales number for one of the products

### Information (if a specific version is affected):
PHP Version: 7.1.4
EDD Version (or branch): `release/3.0`

WordPress Version: Latest

**Comment by sunnyratilal** [comment]
Fixed & merged.
