### ISSUE TITLE
3.0 - Uninstall process doesn't work

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7161]
### Expected behavior
When I have `delete data on uninstall` checked I expect data to be deleted and the plugin to be uninstalled.

### Actual behavior
This admin notice appears:
```
Deletion failed: Internal Server Error
```

And I get this in my error log:

```
[14-Feb-2019 15:08:31 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function edd_get_option() in /var/www/edd/wp-content/plugins/easy-digital-downloads/uninstall.php:30
Stack trace:
#0 /var/www/edd/wp-admin/includes/plugin.php(1018): include()
#1 /var/www/edd/wp-admin/includes/plugin.php(831): uninstall_plugin('easy-digital-do...')
#2 /var/www/edd/wp-admin/includes/ajax-actions.php(3916): delete_plugins(Array)
#3 /var/www/edd/wp-includes/class-wp-hook.php(286): wp_ajax_delete_plugin('')
#4 /var/www/edd/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/edd/wp-admin/admin-ajax.php(100): do_action('wp_ajax_delete-...')
#7 {main}
  thrown in /var/www/edd/wp-content/plugins/easy-digital-downloads/uninstall.php on line 30
```

### Steps to reproduce the behavior
1) Check on `delete data on uninstall` in settings.
2) Deactivate the plugin.
3) Delete the plugin.
4) Error admin notice will appear.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): `release/3.0`

WordPress Version:

Any other relevant information:

I encountered this same bug in RCP and I suspect the cause is the same. In RCP it was due to the new requirements class, which was only loading the main RCP plugin file on `plugins_loaded`, but I don't think this action is triggered during uninstall, so none of the main RCP plugin files were being loaded.

**Comment by cklosowski** [comment]
@nosegraze yeah that combined with the fact that the uninstall hasn't probably been updated for the new table data.

**Comment by pippinsplugins** [comment]
The error is fixed by running the `bootstrap()` method of the core requirements class.

PR created.

**Comment by pippinsplugins** [comment]
@cklosowski we've already updated this for the new tables:
```php
$edd_db_tables = array( 'customers', 'customermeta', 'adjustment', 'adjustmentmeta', 'logs', 'logmeta', 'notes', 'notemeta', 'orders', 'ordermeta', 'order_items', 'order_itemmeta', 'order_adjustments' );
foreach ( $edd_db_tables as $table ) {
	$query = "DROP TABLE IF EXISTS {$wpdb->prefix}edd_{$table}";
	$wpdb->query( $query );
}
```

**Comment by nosegraze** [comment]
In terms of uninstalling, a few tables were still left behind because they were missing from the array. I've pushed up a commit that adds a complete list: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7496/commits/fa7a8ac1a081caf1096ff9707ed0c037b747b547 I've also alphabetized them to make it easier to compare the list with an alphabetical list of tables.

---

On uninstall, I do still get this notice:

```
[18-Dec-2019 14:59:08 UTC] PHP Notice:  get_posts()/get_post()/WP_Query was called <strong>incorrectly</strong>. As of Easy Digital Downloads 3.0, orders no longer exist in the <code>wp_posts</code> table. They have been migrated to <code>wp_edd_orders</code>. Orders should be accessed using <code>edd_get_orders()</code> or <code>edd_get_order()</code>. See https://easydigitaldownloads.com/development/ for more information. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version EDD 3.0.) in /var/www/wp/wp-includes/functions.php on line 4778
[18-Dec-2019 14:59:08 UTC] PHP Stack trace:
[18-Dec-2019 14:59:08 UTC] PHP   1. {main}() /var/www/wp/wp-admin/admin-ajax.php:0
[18-Dec-2019 14:59:08 UTC] PHP   2. do_action() /var/www/wp/wp-admin/admin-ajax.php:173
[18-Dec-2019 14:59:08 UTC] PHP   3. WP_Hook->do_action() /var/www/wp/wp-includes/plugin.php:465
[18-Dec-2019 14:59:08 UTC] PHP   4. WP_Hook->apply_filters() /var/www/wp/wp-includes/class-wp-hook.php:310
[18-Dec-2019 14:59:08 UTC] PHP   5. wp_ajax_delete_plugin() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP   6. delete_plugins() /var/www/wp/wp-admin/includes/ajax-actions.php:4310
[18-Dec-2019 14:59:08 UTC] PHP   7. uninstall_plugin() /var/www/wp/wp-admin/includes/plugin.php:934
[18-Dec-2019 14:59:08 UTC] PHP   8. include() /var/www/wp/wp-admin/includes/plugin.php:1192
[18-Dec-2019 14:59:08 UTC] PHP   9. get_posts() /var/www/wp/wp-content/plugins/easy-digital-downloads/uninstall.php:41
[18-Dec-2019 14:59:08 UTC] PHP  10. WP_Query->query() /var/www/wp/wp-includes/post.php:1961
[18-Dec-2019 14:59:08 UTC] PHP  11. WP_Query->get_posts() /var/www/wp/wp-includes/class-wp-query.php:3403
[18-Dec-2019 14:59:08 UTC] PHP  12. do_action_ref_array() /var/www/wp/wp-includes/class-wp-query.php:1752
[18-Dec-2019 14:59:08 UTC] PHP  13. WP_Hook->do_action() /var/www/wp/wp-includes/plugin.php:531
[18-Dec-2019 14:59:08 UTC] PHP  14. WP_Hook->apply_filters() /var/www/wp/wp-includes/class-wp-hook.php:310
[18-Dec-2019 14:59:08 UTC] PHP  15. EDD\Compat\Payment->pre_get_posts() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP  16. _doing_it_wrong() /var/www/wp/wp-content/plugins/easy-digital-downloads/includes/compat/class-payment.php:116
[18-Dec-2019 14:59:08 UTC] PHP  17. trigger_error() /var/www/wp/wp-includes/functions.php:4778
```

Caused by this line:

```php
$items = get_posts( array( 'post_type' => $post_type, 'post_status' => 'any', 'numberposts' => -1, 'fields' => 'ids' ) );
```

It's not an issue really, but worth noting. It's due to deleting these post types, which are no longer post types: `'edd_payment', 'edd_discount', 'edd_log'`, but are stored in custom tables.

I'm not sure if that's still needed to clean up legacy data that may not have been deleted in the migration?

---

I also got these, notices, but I don't think they're related to uninstall specifically. I think they're more generic issues in the backwards compatibility layer, so I'll log them separately.

```
[18-Dec-2019 14:59:08 UTC] PHP Notice:  Trying to get property 'columns' of non-object in /var/www/wp/wp-content/plugins/easy-digital-downloads/includes/compat/class-discount.php on line 240
[18-Dec-2019 14:59:08 UTC] PHP Stack trace:
[18-Dec-2019 14:59:08 UTC] PHP   1. {main}() /var/www/wp/wp-admin/admin-ajax.php:0
[18-Dec-2019 14:59:08 UTC] PHP   2. do_action() /var/www/wp/wp-admin/admin-ajax.php:173
[18-Dec-2019 14:59:08 UTC] PHP   3. WP_Hook->do_action() /var/www/wp/wp-includes/plugin.php:465
[18-Dec-2019 14:59:08 UTC] PHP   4. WP_Hook->apply_filters() /var/www/wp/wp-includes/class-wp-hook.php:310
[18-Dec-2019 14:59:08 UTC] PHP   5. wp_ajax_delete_plugin() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP   6. delete_plugins() /var/www/wp/wp-admin/includes/ajax-actions.php:4310
[18-Dec-2019 14:59:08 UTC] PHP   7. uninstall_plugin() /var/www/wp/wp-admin/includes/plugin.php:934
[18-Dec-2019 14:59:08 UTC] PHP   8. include() /var/www/wp/wp-admin/includes/plugin.php:1192
[18-Dec-2019 14:59:08 UTC] PHP   9. get_posts() /var/www/wp/wp-content/plugins/easy-digital-downloads/uninstall.php:41
[18-Dec-2019 14:59:08 UTC] PHP  10. WP_Query->query() /var/www/wp/wp-includes/post.php:1961
[18-Dec-2019 14:59:08 UTC] PHP  11. WP_Query->get_posts() /var/www/wp/wp-includes/class-wp-query.php:3403
[18-Dec-2019 14:59:08 UTC] PHP  12. apply_filters_ref_array() /var/www/wp/wp-includes/class-wp-query.php:2901
[18-Dec-2019 14:59:08 UTC] PHP  13. WP_Hook->apply_filters() /var/www/wp/wp-includes/plugin.php:251
[18-Dec-2019 14:59:08 UTC] PHP  14. EDD\Compat\Discount->posts_request() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/wp/wp-includes/class-wp-list-util.php on line 150
[18-Dec-2019 14:59:08 UTC] PHP Stack trace:
[18-Dec-2019 14:59:08 UTC] PHP   1. {main}() /var/www/wp/wp-admin/admin-ajax.php:0
[18-Dec-2019 14:59:08 UTC] PHP   2. do_action() /var/www/wp/wp-admin/admin-ajax.php:173
[18-Dec-2019 14:59:08 UTC] PHP   3. WP_Hook->do_action() /var/www/wp/wp-includes/plugin.php:465
[18-Dec-2019 14:59:08 UTC] PHP   4. WP_Hook->apply_filters() /var/www/wp/wp-includes/class-wp-hook.php:310
[18-Dec-2019 14:59:08 UTC] PHP   5. wp_ajax_delete_plugin() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP   6. delete_plugins() /var/www/wp/wp-admin/includes/ajax-actions.php:4310
[18-Dec-2019 14:59:08 UTC] PHP   7. uninstall_plugin() /var/www/wp/wp-admin/includes/plugin.php:934
[18-Dec-2019 14:59:08 UTC] PHP   8. include() /var/www/wp/wp-admin/includes/plugin.php:1192
[18-Dec-2019 14:59:08 UTC] PHP   9. get_posts() /var/www/wp/wp-content/plugins/easy-digital-downloads/uninstall.php:41
[18-Dec-2019 14:59:08 UTC] PHP  10. WP_Query->query() /var/www/wp/wp-includes/post.php:1961
[18-Dec-2019 14:59:08 UTC] PHP  11. WP_Query->get_posts() /var/www/wp/wp-includes/class-wp-query.php:3403
[18-Dec-2019 14:59:08 UTC] PHP  12. apply_filters_ref_array() /var/www/wp/wp-includes/class-wp-query.php:2901
[18-Dec-2019 14:59:08 UTC] PHP  13. WP_Hook->apply_filters() /var/www/wp/wp-includes/plugin.php:251
[18-Dec-2019 14:59:08 UTC] PHP  14. EDD\Compat\Discount->posts_request() /var/www/wp/wp-includes/class-wp-hook.php:286
[18-Dec-2019 14:59:08 UTC] PHP  15. wp_list_pluck() /var/www/wp/wp-content/plugins/easy-digital-downloads/includes/compat/class-discount.php:240
[18-Dec-2019 14:59:08 UTC] PHP  16. WP_List_Util->pluck() /var/www/wp/wp-includes/functions.php:4262
```

**Comment by pippinsplugins** [comment]
Ideally that old post data doesn't exist anymore but I can definitely foresee cases where it will still be around.

I think we have three options:

1. Ignore them
2. Delete through direct SQL queries (sucks for meta)
3. Re-register the post types during the uninstall process so they become available temporarily

**Comment by cklosowski** [comment]
None of those options are amazing @pippinsplugins but I think the best solution would be to re-register the post type (temporarily if possible) and then allow them to be removed that way. This would be slower that direct queries, but will leave less abandoned data and counts in taxonomies.

**Comment by nosegraze** [comment]
Updated with two changes:

1. Don't load the compatibility classes during EDD uninstall. This fixes the above mentioned issues of post type warnings. Now I can confirm that EDD post types get deleted and no notices are logged.
2. I reworked the custom table uninstall to loop through all registered components and use the BerlinDB `uninstall()` method. This drops the table and removes the option with the version number. One thing to be wary of though: this would drop any tables added by third party plugins using the new `edd_register_component()` function. With that in mind, would a hard-coded list be preferred?

**Comment by nosegraze** [comment]
@cklosowski Works for me! :+1:
